import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Dev: set OBSIDIAN_PLUGIN_DIR to <vault>/.obsidian/plugins/festa to build straight into a vault.
const pluginDir = !prod && process.env.OBSIDIAN_PLUGIN_DIR;
if (pluginDir) mkdirSync(pluginDir, { recursive: true });

const copyAssets = {
	name: 'copy-assets',
	setup(build) {
		build.onEnd((result) => {
			if (!pluginDir || result.errors.length) return;
			for (const f of ['manifest.json', 'styles.css']) copyFileSync(f, join(pluginDir, f));
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: pluginDir ? join(pluginDir, 'main.js') : 'main.js',
	plugins: [copyAssets],
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
