// Generated by scripts/generate.py. Do not edit.
import type { YearRow } from "../types";
import y2020 from "./years/2020.json";
import y2021 from "./years/2021.json";
import y2022 from "./years/2022.json";
import y2023 from "./years/2023.json";
import y2024 from "./years/2024.json";
import y2025 from "./years/2025.json";
import y2026 from "./years/2026.json";
import y2027 from "./years/2027.json";
import y2028 from "./years/2028.json";
import y2029 from "./years/2029.json";
import y2030 from "./years/2030.json";
import y2031 from "./years/2031.json";
import y2032 from "./years/2032.json";
import y2033 from "./years/2033.json";
import y2034 from "./years/2034.json";
import y2035 from "./years/2035.json";
import y2036 from "./years/2036.json";
import y2037 from "./years/2037.json";
import y2038 from "./years/2038.json";
import y2039 from "./years/2039.json";
import y2040 from "./years/2040.json";

export const YEARS: Record<number, YearRow[]> = {
	2020: y2020 as unknown as YearRow[],
	2021: y2021 as unknown as YearRow[],
	2022: y2022 as unknown as YearRow[],
	2023: y2023 as unknown as YearRow[],
	2024: y2024 as unknown as YearRow[],
	2025: y2025 as unknown as YearRow[],
	2026: y2026 as unknown as YearRow[],
	2027: y2027 as unknown as YearRow[],
	2028: y2028 as unknown as YearRow[],
	2029: y2029 as unknown as YearRow[],
	2030: y2030 as unknown as YearRow[],
	2031: y2031 as unknown as YearRow[],
	2032: y2032 as unknown as YearRow[],
	2033: y2033 as unknown as YearRow[],
	2034: y2034 as unknown as YearRow[],
	2035: y2035 as unknown as YearRow[],
	2036: y2036 as unknown as YearRow[],
	2037: y2037 as unknown as YearRow[],
	2038: y2038 as unknown as YearRow[],
	2039: y2039 as unknown as YearRow[],
	2040: y2040 as unknown as YearRow[],
};
